version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: sentinel-postgres
    environment:
      POSTGRES_PASSWORD: kurisu
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: